#!/bin/sh
#
# An example hook script to prepare the commit log message.
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.
#
# The first one 

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Removes the "# Please enter the commit message..." help message.
/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

# Adds the Conventional Commits reminder.
echo "# Follow the Conventional Commits 1.0.0." >> $COMMIT_MSG_FILE
echo "# [www.conventionalcommits.org]." >> $COMMIT_MSG_FILE